---
- name: Configurar sudoers con Ansible
  hosts: servidor
  remote_user: usuario
  become: yes
  tasks:
    - name: Añadir permisos para usuario en sudoers
      become: yes
      lineinfile:
        dest: /etc/sudoers
        insertafter: 'root\tALL=(ALL:ALL) ALL'
        line: 'usuario ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Añadir permisos para grupo sudo en sudoers
      become: yes
      lineinfile:
        dest: /etc/sudoers
        insertafter: '%sudo   ALL=(ALL:ALL) ALL'
        line: '%sudo   ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'


    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes

    - name: Instalar paquetes necesarios
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - git
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql

    - name: Descargar imagen de Docker
      shell: docker pull itzg/minecraft-server
      become: yes

    - name: Limpiar el directorio HTML
      file:
        path: /var/www/html
        state: absent
      become: yes

    - name: Crear el directorio HTML
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
      become: yes

    - name: Clonar repositorio de HTML
      git:
        repo: https://github.com/hammad2003/smai.git
        dest: /var/www/html/smai
        force: yes
      become: yes

    - name: Mover archivos del repositorio a la carpeta de Apache
      shell: mv /var/www/html/smai/* /var/www/html/ && rm -rf /var/www/html/smai
      become: yes

    - name: Cambiar propietario y grupo de /var/www/html/mods
      file:
        path: /var/www/html/mods
        owner: usuario
        group: usuario
        recurse: yes
        mode: "0775"
      become: yes

    - name: Cambiar propietario y grupo de /var/www/html/plugins
      file:
        path: /var/www/html/plugins
        owner: usuario
        group: usuario
        recurse: yes
        mode: "0775"
      become: yes

    - name: Crear base de datos y usuario
      shell: |
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS smai;"
        mysql -u root -e "CREATE USER IF NOT EXISTS 'usuario'@'localhost' IDENTIFIED WITH mysql_native_password BY 'usuario';"
        mysql -u root -e "GRANT ALL ON smai.* to 'usuario'@'localhost';"
      become: yes

    - name: Borrar las tablas
      shell: |
        mysql -u usuario -pusuario -D smai -e "DROP TABLE IF EXISTS server_properties;"
        mysql -u usuario -pusuario -D smai -e "DROP TABLE IF EXISTS servidores;"
        mysql -u usuario -pusuario -D smai -e "DROP TABLE IF EXISTS usuarios;"
      become: yes

    - name: Crear las tablas
      shell: |
        mysql -u usuario -pusuario -D smai -e "CREATE TABLE IF NOT EXISTS usuarios (
          id INT AUTO_INCREMENT PRIMARY KEY,
          nombre VARCHAR(255),
          correo VARCHAR(255) UNIQUE,
          contrasena VARCHAR(255),
          servidores_creados INT DEFAULT 0
        );"

        mysql -u usuario -pusuario -D smai -e "CREATE TABLE IF NOT EXISTS servidores (
          id INT AUTO_INCREMENT PRIMARY KEY,
          nombre VARCHAR(255),
          software VARCHAR(50),
          version VARCHAR(20),
          id_usuario INT,
          container_id VARCHAR(255),
          estado VARCHAR(20) DEFAULT 'Detenido',
          ip_address VARCHAR(255),
          puerto INT,
          FOREIGN KEY (id_usuario) REFERENCES usuarios(id)
        );"
        
        mysql -u usuario -pusuario -D smai -e "CREATE TABLE IF NOT EXISTS server_properties (
          id INT AUTO_INCREMENT PRIMARY KEY,
          server_id INT,
          difficulty ENUM('hard', 'normal', 'easy', 'peaceful') DEFAULT 'easy',
          mode ENUM('creative', 'survival', 'adventure', 'spectator') DEFAULT 'survival',
          max_players INT DEFAULT 20,
          max_build_height INT DEFAULT 256,
          view_distance INT DEFAULT 10,
          spawn_npcs BOOLEAN DEFAULT TRUE,
          allow_nether BOOLEAN DEFAULT TRUE,
          spawn_animals BOOLEAN DEFAULT TRUE,
          spawn_monsters BOOLEAN DEFAULT TRUE,
          pvp BOOLEAN DEFAULT TRUE,
          enable_command_block BOOLEAN DEFAULT FALSE,
          allow_flight BOOLEAN DEFAULT TRUE,
          FOREIGN KEY (server_id) REFERENCES servidores(id)  
        );"
      become: yes